In [ ]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
print(array)

In [3]:
import numpy as np
array_zeros = np.zeros((3, 5))
print(array_zeros)

array_ones = np.ones((3, 5))
print(array_ones)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np

In [5]:
import numpy as np
arr= ([1,2,3,6,7])
print(arr[2:5])

[3, 6, 7]


In [31]:
import numpy as np
array = np.full((3, 5), 7)
print(arr[(2:5), (0:3)]


SyntaxError: invalid syntax (3808302250.py, line 3)